version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  spotus_django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: spotus_local_django
    depends_on:
      - spotus_postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start
    networks:
      default:
        aliases:
          - dev.spot.us
      squarelet_default:
        aliases:
          - dev.spot.us

  spotus_postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: spotus_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  spotus_redis:
    image: redis:5.0

  spotus_celeryworker:
    <<: *django
    image: spotus_local_celeryworker
    depends_on:
      - spotus_redis
      - spotus_postgres
    ports: []
    command: /start-celeryworker

  spotus_celerybeat:
    <<: *django
    image: spotus_local_celerybeat
    depends_on:
      - spotus_redis
      - spotus_postgres
    ports: []
    command: /start-celerybeat

networks:
  squarelet_default:
    external: true
