# Generated by Django 3.0.5 on 2020-04-23 12:25

# Django
import django.contrib.postgres.fields.citext
import django.utils.timezone
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models

# Standard Library
import uuid

# Third Party
import squarelet_auth.fields


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        CITextExtension(),
        migrations.AlterModelOptions(name="user", options={"ordering": ("username",)}),
        migrations.AlterModelManagers(name="user", managers=[]),
        migrations.RemoveField(model_name="user", name="date_joined"),
        migrations.RemoveField(model_name="user", name="first_name"),
        migrations.RemoveField(model_name="user", name="last_name"),
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                help_text="A URL which points to an avatar for the user",
                max_length=255,
                verbose_name="avatar url",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=squarelet_auth.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Timestamp of when the user was created",
                verbose_name="created at",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_failed",
            field=models.BooleanField(
                default=False,
                help_text="Has an email we sent to this user's email address failed?",
                verbose_name="email failed",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Has this user's email address been verified?",
                verbose_name="email verified",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=squarelet_auth.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Timestamp of when the user was last updated",
                verbose_name="updated at",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="use_autologin",
            field=models.BooleanField(
                default=True,
                help_text="Links you receive in emails from us will contain a token to automatically log you in",
                verbose_name="use autologin",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique ID to link users across MuckRock's sites",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=django.contrib.postgres.fields.citext.CIEmailField(
                help_text="The user's primary email address",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                help_text="The user's full name",
                max_length=255,
                verbose_name="full name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=django.contrib.postgres.fields.citext.CICharField(
                help_text="A unique public identifier for the user",
                max_length=150,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
