# Generated by Django 3.0.5 on 2020-04-23 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('squarelet_auth_organizations', '0002_auto_20200423_1008'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(help_text='The subscription type for this organization', null=True, on_delete=django.db.models.deletion.PROTECT, to='squarelet_auth_organizations.Plan', verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(help_text='The users who are members of this organization', related_name='organizations', through='squarelet_auth_organizations.Membership', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
