# Generated by Django 3.0.5 on 2020-05-28 17:49

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squarelet_auth_organizations", "0006_auto_20200527_1646"),
        ("organizations", "0002_auto_20200423_1441"),
    ]
    run_before = [("squarelet_auth_organizations", "0007_delete_plan")]

    operations = [
        migrations.RemoveField(model_name="organization", name="plan"),
        migrations.AddField(
            model_name="organization",
            name="entitlement",
            field=models.ForeignKey(
                help_text="The subscription type for this organization",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="squarelet_auth_organizations.Entitlement",
                verbose_name="entitlement",
            ),
        ),
    ]
